version: '3'
services:
  gazebo_simulator:
    build: .
    image: eugen06/bfmc2025:latest
    container_name: gazebo_simulator
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/eugen/Desktop/bfmc_2025:/root/catkin_ws/src
    #  - /home/eugen/catkin_ws/src:/root/catkin_ws/src
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    shm_size: '6gb'
